version : '2.1'
services:
  # Website
  web:
    # depend on db service to run
    depends_on:
        - db
    build: .
    ports: 
        - "4500:4500"
    # Auto fill datasource url 127.[16-*].0.[0-*] for Unix -> new network everytime down and up
    # Auto fill datasource url based on network 192.168.99.100 for window
    environment: 
        SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://db:3306/mysqldocker"
            }'
    
        
    # Database
  db:
    image: mysql
    environment:
        - MYSQL_DATABASE=mysqldocker
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_HOST=localhost
        - MYSQL_PORT=3306
        - MYSQL_USER=mysqldocker
        - MYSQL_PASSWORD=mysql
        - MYSQL_MY_DATABASE=my-database
    ports: 
        - "3306:3306"
    volumes:
        - "../DockerVolumes/mysql"
        